### ISSUE TITLE
[Question] What's wrong with the naming and organization of the source code?

### ISSUE THREAD

**Issue by arthurgubaidullin** [fp-ts/core#41]
@gcanti Hi. You are doing a very important job!

I have questions.

Why is the package called core? What does this mean?

It means absolutely nothing to me. And even if I find out, I will quickly forget it. Because this name doesn't scream anything! The history of monads teaches nothing?

Why is the organization called `fp-ts`? What is it goal? The title means nothing.

Why such an organization of source codes? Why not a mono repository?

I don't want to read in the blogs in the next few years about where it's in which repository and what its name means. It's horrible.

If I need `pipe` and `Option`, I want to just import `@fp-ts/function` and `@fp-ts/Option`. Nothing else is needed. I don't understand why I have to wait for a big release of `@fp-ts/core` or `@fp-ts/data` or where they are!

Thanks for any replies.

**Comment by gcanti** [comment]
[`fp-ts`](https://github.com/gcanti/fp-ts) is one of my personal projects dedicated to functional programming that has been around for several years now. The `fp-ts` organization represents the next major iteration of [`fp-ts`](https://github.com/gcanti/fp-ts) and its objective is a reconciliation with [`Effect`](https://github.com/Effect-TS) in order to unify the ecosystems.

The current situation of repositories and packages is still temporary as they are still under heavy development, and packages are primarily published for early feedback and for contributors. Therefore, I suggest not focusing on the current situation, but rather making proposals that can be considered and discussed.

**Comment by kirit0s** [comment]
Thank you for clarifying the current situation. Maybe enabled github Discussions?

**Comment by arthurgubaidullin** [comment]
@gcanti Thank you.

Can you suggest the best place to submit proposals?

**Comment by gcanti** [comment]
A simple issue like this is fine for start

**Comment by mikearnaldi** [comment]
> If I need `pipe` and `Option`, I want to just import `@fp-ts/function` and `@fp-ts/Option`. Nothing else is needed. I don't understand why I have to wait for a big release of `@fp-ts/core` or `@fp-ts/data` or where they are!

That is a very simplistic view that doesn't account for the fact that each module has dependencies on other modules, you wouldn't be able to use `@fp-ts/Either` without `@fp-ts/Option` + `@fp-ts/Monad` + a few hundreds.

**Comment by mikearnaldi** [comment]
Same as #42, discussion there

**Comment by arthurgubaidullin** [comment]
> That is a very simplistic view that doesn't account for the fact that each module has dependencies on other modules, you wouldn't be able to use @fp-ts/Either without @fp-ts/Option + @fp-ts/Monad + a few hundreds.

@mikearnaldi, thank you for a response. I, as a consumer, only want to depend on the code I use, it's fine if I have to install peer dependencies.

Also I don't want to wait for a "big" release. Obviously the things I use already should be usable.

This is where the naming problem comes from. How do I figure out what to import without reading your blog post? Most likely there will be no other documentation.

I want to understand what is there by the structure of the project.

If at the very top of the hierarchy are meaningless common names, then I simply will not have a chance. I am not the developer of the `fp-ts` library, I do not know its structure and will never know.

I don't understand why the project is not being developed through trunk based development.

Why do I need `O.fromEither`, I can live with `optionFromEither`. And let it lie in `either-to-option` package. I'm tired of converting and renaming imports to namespaces.

Maybe I'm being too harsh. I'm just not a native speaker and it's hard for me to express my thoughts clearly and without harshness. I hope that fp-ts will develop and live. ❤️

**Comment by mikearnaldi** [comment]
"This is where the naming problem comes from. How do I figure out what to import without reading your blog post? Most likely there will be no other documentation."

You assume a lot, there will be documentation.

"Why do I need O.fromEither, I can live with optionFromEither. And let it lie in either-to-option package. I'm tired of converting and renaming imports to namespaces."

Having different preferences is fine, I'd encourage trying to write a library if you believe that this naming is better.

Please find following the reference docs of every module present in the ecosystem:

https://fp-ts.github.io/core/docs/modules
https://fp-ts.github.io/schema/docs/modules
https://fp-ts.github.io/optic/docs/modules
https://effect-ts.github.io/data/docs/modules
https://effect-ts.github.io/io/docs/modules
https://effect-ts.github.io/stm/docs/modules
https://effect-ts.github.io/stream/docs/modules
https://effect-ts.github.io/query/docs/modules
https://effect-ts.github.io/cache/docs/modules
